export const EVENT_CHAT = "EVENT_CHAT";
export const EVENT_UPDATE_USER_LIST = "EVENT_UPDATE_USER_LIST";
export const EVENT_CHAT_FROM_SERVER = "EVENT_CHAT_FROM_SERVER";
export const EVENT_UPDATE_USER_LIST_FROM_SERVER = "EVENT_UPDATE_USER_LIST_FROM_SERVER";
