export const EVENT_CHAT = "EVENT_CHAT";
export const EVENT_LOGIN = "EVENT_LOGIN";
export const EVENT_CHAT_FROM_SERVER = "EVENT_CHAT_FROM_SERVER";
export const EVENT_LOGIN_FROM_SERVER = "EVENT_LOGIN_FROM_SERVER";
